# This is the Travis CI config file which tells Travis what to do whenever we push changes to the project repo

language: python
python:
    - "3.6"

services:
  - docker

before_script: pip install docker-compose

script: 
  - docker-compose run app sh -c "python manage.py test --ignore=E501,E111 && flake8"